@startuml

' =========================
' Core Domain
' =========================

' parses assembly code corresponding to a Team 
' and extracts Instruction 
class Disassembler {
    - parseAssembly(code : String) : List<Instruction>
}

' Analyzes a list of Instructions and extracts features to add 
' to the FeatureVector to the Uarch
class FeaturesAnalyzer{
    - analyzeBasicBlock(instructions : List<Instruction>) : FeatureVector 
}

class FeatureVector{
    values : Map<String, Float>  
}

' takes latency results from a team (avgCycles)
' takes FeatureTable 
' fits coefficients 
class Regressor{
    ' weights = { "ADD_count": 0.12, "LOAD_count": 1.85, "RAW_hazards": 3.40, "ADD_ADD_transition": 0.75'
    - weights: Map<String, Float>
    - bias: Float
    - fit (features: List<FeatureVector>, latencies: List<Float>) : void 
    - predict(feature: FeatureVector) : Float
}

class Uarch {
    name : String
    isa : String
    abi : String
    FeatureTable : List<FeatureVector>
}

class TPG{
    name : String
    dtype : String
    GPIS : List<String>
}

class InferenceResult {
}

class instrTraversal {
    idTraversal : Integer
    count : Integer
    avgCycles : Integer
    stdDevCycles : Integer
}

class instrTeam {
    idTeam : Integer
    count : Integer
    avgCycles : Integer
    stdDevCycles : Integer
}

class Instruction {
    mnemonic : String
    operands : List<String>
    immediate : String
    ' raw code 
    code : String
}

class Team {
    id : Integer
    idProgs : List<Integer>
}


' =========================
' Aggregates
' =========================

class TraversalLevelTPG {
    inferenceAvgCycles : Integer
    inferenceStdDevCycles : Integer
}

class TeamLevelTPG{
    inferenceAvgCycles : Integer
    inferenceStdDevCycles : Integer
}

class Assembly{
    code : String
}

' =========================
' Relationships
' =========================

InferenceResult "1" *-- "1" TraversalLevelTPG
InferenceResult "1" *-- "1" TeamLevelTPG

TraversalLevelTPG "1" *-- "1..*" instrTraversal
TeamLevelTPG "1" *-- "1..*" instrTeam
TeamLevelTPG "1" *-- "1..*" instrTraversal

Team "1" *-- "1" instrTeam

Team "1" *-- "1..*" Instruction

TPG "1" *-- "1" InferenceResult

TPG "1" *-- "1..*" Team

Uarch "1" *-- "1..*" InferenceResult

Disassembler ..> Instruction : produces
Assembly ..> Disassembler : takes

FeaturesAnalyzer ..> Uarch : produces
Instruction ..> FeaturesAnalyzer : takes

Team "1" *-- "1" Assembly

@enduml